# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import pool_manager_pb2 as pool__manager__pb2


class PoolManagerStub(object):
    """Define the Pool Manager service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUtilizations = channel.unary_unary(
                '/pool_manager.PoolManager/GetUtilizations',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=pool__manager__pb2.UpdateUtilizationsResponse.FromString,
                )


class PoolManagerServicer(object):
    """Define the Pool Manager service
    """

    def GetUtilizations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PoolManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUtilizations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUtilizations,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=pool__manager__pb2.UpdateUtilizationsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pool_manager.PoolManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PoolManager(object):
    """Define the Pool Manager service
    """

    @staticmethod
    def GetUtilizations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pool_manager.PoolManager/GetUtilizations',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pool__manager__pb2.UpdateUtilizationsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
