# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pool_manager.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12pool_manager.proto\x12\x0cpool_manager\x1a\x1bgoogle/protobuf/empty.proto\"\xb1\x01\n\x0fPoolUtilization\x12\x0f\n\x07pool_id\x18\x01 \x01(\t\x12\x1e\n\x16num_served_invocations\x18\x02 \x01(\x05\x12\x18\n\x10\x61vg_waiting_time\x18\x03 \x01(\x01\x12+\n#num_invocations_lower_freq_possible\x18\x04 \x01(\x05\x12&\n\x1enum_invocations_increased_freq\x18\x05 \x01(\x05\"p\n\x0eNodeAssignment\x12\x0f\n\x07pool_id\x18\x01 \x01(\t\x12\x11\n\tnum_cores\x18\x02 \x01(\x05\x12\x10\n\x08start_id\x18\x03 \x01(\x05\x12\x17\n\x0f\x66requency_level\x18\x04 \x01(\x05\x12\x0f\n\x07message\x18\x05 \x01(\t\"P\n\x19UpdateUtilizationsRequest\x12\x33\n\x0cutilizations\x18\x01 \x03(\x0b\x32\x1d.pool_manager.PoolUtilization\"`\n\x1aUpdateUtilizationsResponse\x12\x31\n\x0b\x61ssignments\x18\x01 \x03(\x0b\x32\x1c.pool_manager.NodeAssignment\x12\x0f\n\x07message\x18\x02 \x01(\t2b\n\x0bPoolManager\x12S\n\x0fGetUtilizations\x12\x16.google.protobuf.Empty\x1a(.pool_manager.UpdateUtilizationsResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pool_manager_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POOLUTILIZATION._serialized_start=66
  _POOLUTILIZATION._serialized_end=243
  _NODEASSIGNMENT._serialized_start=245
  _NODEASSIGNMENT._serialized_end=357
  _UPDATEUTILIZATIONSREQUEST._serialized_start=359
  _UPDATEUTILIZATIONSREQUEST._serialized_end=439
  _UPDATEUTILIZATIONSRESPONSE._serialized_start=441
  _UPDATEUTILIZATIONSRESPONSE._serialized_end=537
  _POOLMANAGER._serialized_start=539
  _POOLMANAGER._serialized_end=637
# @@protoc_insertion_point(module_scope)
