apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: web-serve
  namespace: default
spec:
  template:
    spec:
      containerConcurrency: 1000
      containers:
        - image: jovanvr97/web_serve_knative
    metadata:
      annotations:
        autoscaling.knative.dev/target: "1000"
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "1h"
