# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workflow_controller.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19workflow_controller.proto\x12\x12workflowcontroller\"1\n\x0fOptimizeRequest\x12\x11\n\tfunctions\x18\x01 \x03(\t\x12\x0b\n\x03slo\x18\x02 \x01(\x01\"z\n\x10\x46unctionDeadline\x12\x15\n\rfunction_name\x18\x01 \x01(\t\x12\x11\n\tfrequency\x18\x02 \x01(\x01\x12\x11\n\texec_time\x18\x03 \x01(\x01\x12\x0e\n\x06\x65nergy\x18\x04 \x01(\x01\x12\x19\n\x11\x64\x65\x61\x64line_fraction\x18\x05 \x01(\x01\"\x90\x01\n\x10OptimizeResponse\x12\x37\n\tdeadlines\x18\x01 \x03(\x0b\x32$.workflowcontroller.FunctionDeadline\x12\x1c\n\x14total_execution_time\x18\x02 \x01(\x01\x12\x14\n\x0ctotal_energy\x18\x03 \x01(\x01\x12\x0f\n\x07message\x18\x04 \x01(\t2t\n\x12WorkflowController\x12^\n\x11OptimizeDeadlines\x12#.workflowcontroller.OptimizeRequest\x1a$.workflowcontroller.OptimizeResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'workflow_controller_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OPTIMIZEREQUEST._serialized_start=49
  _OPTIMIZEREQUEST._serialized_end=98
  _FUNCTIONDEADLINE._serialized_start=100
  _FUNCTIONDEADLINE._serialized_end=222
  _OPTIMIZERESPONSE._serialized_start=225
  _OPTIMIZERESPONSE._serialized_end=369
  _WORKFLOWCONTROLLER._serialized_start=371
  _WORKFLOWCONTROLLER._serialized_end=487
# @@protoc_insertion_point(module_scope)
