# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import workflow_controller_pb2 as workflow__controller__pb2


class WorkflowControllerStub(object):
    """The WorkflowController service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OptimizeDeadlines = channel.unary_unary(
                '/workflowcontroller.WorkflowController/OptimizeDeadlines',
                request_serializer=workflow__controller__pb2.OptimizeRequest.SerializeToString,
                response_deserializer=workflow__controller__pb2.OptimizeResponse.FromString,
                )


class WorkflowControllerServicer(object):
    """The WorkflowController service definition.
    """

    def OptimizeDeadlines(self, request, context):
        """Optimizes per-function deadlines based on the provided functions and SLO.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkflowControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OptimizeDeadlines': grpc.unary_unary_rpc_method_handler(
                    servicer.OptimizeDeadlines,
                    request_deserializer=workflow__controller__pb2.OptimizeRequest.FromString,
                    response_serializer=workflow__controller__pb2.OptimizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'workflowcontroller.WorkflowController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WorkflowController(object):
    """The WorkflowController service definition.
    """

    @staticmethod
    def OptimizeDeadlines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/workflowcontroller.WorkflowController/OptimizeDeadlines',
            workflow__controller__pb2.OptimizeRequest.SerializeToString,
            workflow__controller__pb2.OptimizeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
