apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ml-train
  namespace: default
spec:
  template:
    spec:
      containerConcurrency: 1000
      containers:
        - image: jovanvr97/ml_train_knative:latest
    metadata:
      annotations:
        autoscaling.knative.dev/target: "1000"
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "1h"
