# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pool_controller.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15pool_controller.proto\x12\x0fpool_controller\x1a\x1bgoogle/protobuf/empty.proto\"0\n\x0f\x46unctionRequest\x12\x0b\n\x03pid\x18\x01 \x01(\t\x12\x10\n\x08\x64\x65\x61\x64line\x18\x02 \x01(\x05\"S\n\x13\x43oreFrequencyUpdate\x12\x15\n\rstart_core_id\x18\x01 \x01(\x05\x12\x12\n\ncore_count\x18\x02 \x01(\x05\x12\x11\n\tfrequency\x18\x03 \x01(\x05\"L\n\rRequestUpdate\x12\x0b\n\x03pid\x18\x01 \x01(\t\x12.\n\x06status\x18\x02 \x01(\x0e\x32\x1e.pool_controller.RequestStatus\"z\n\x0fUtilizationData\x12\x17\n\x0fserved_requests\x18\x01 \x01(\x05\x12\x18\n\x10\x61vg_waiting_time\x18\x02 \x01(\x02\x12\x17\n\x0fmissed_requests\x18\x03 \x01(\x05\x12\x1b\n\x13temp_freq_increases\x18\x04 \x01(\x05*R\n\rRequestStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07RUNNING\x10\x01\x12\x0b\n\x07\x42LOCKED\x10\x02\x12\x0b\n\x07WAITING\x10\x03\x12\r\n\tCOMPLETED\x10\x04\x32\xdb\x03\n\x0ePoolController\x12\x46\n\nAddRequest\x12 .pool_controller.FunctionRequest\x1a\x16.google.protobuf.Empty\x12\x46\n\x0c\x42lockRequest\x12\x1e.pool_controller.RequestUpdate\x1a\x16.google.protobuf.Empty\x12H\n\x0eUnblockRequest\x12\x1e.pool_controller.RequestUpdate\x1a\x16.google.protobuf.Empty\x12I\n\x0f\x43ompleteRequest\x12\x1e.pool_controller.RequestUpdate\x1a\x16.google.protobuf.Empty\x12S\n\x13UpdateCoreFrequency\x12$.pool_controller.CoreFrequencyUpdate\x1a\x16.google.protobuf.Empty\x12O\n\x13SendUtilizationData\x12 .pool_controller.UtilizationData\x1a\x16.google.protobuf.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pool_controller_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTSTATUS._serialized_start=408
  _REQUESTSTATUS._serialized_end=490
  _FUNCTIONREQUEST._serialized_start=71
  _FUNCTIONREQUEST._serialized_end=119
  _COREFREQUENCYUPDATE._serialized_start=121
  _COREFREQUENCYUPDATE._serialized_end=204
  _REQUESTUPDATE._serialized_start=206
  _REQUESTUPDATE._serialized_end=282
  _UTILIZATIONDATA._serialized_start=284
  _UTILIZATIONDATA._serialized_end=406
  _POOLCONTROLLER._serialized_start=493
  _POOLCONTROLLER._serialized_end=968
# @@protoc_insertion_point(module_scope)
