# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node_controller.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15node_controller.proto\x12\x0enodecontroller\"\xb1\x01\n\x0fPoolUtilization\x12\x0f\n\x07pool_id\x18\x01 \x01(\t\x12\x1e\n\x16num_served_invocations\x18\x02 \x01(\x05\x12\x18\n\x10\x61vg_waiting_time\x18\x03 \x01(\x01\x12+\n#num_invocations_lower_freq_possible\x18\x04 \x01(\x05\x12&\n\x1enum_invocations_increased_freq\x18\x05 \x01(\x05\"8\n\nAssignment\x12\x11\n\tnum_cores\x18\x01 \x01(\x05\x12\x17\n\x0f\x66requency_level\x18\x02 \x01(\x05\"T\n\x1cUpdatePoolUtilizationRequest\x12\x34\n\x0butilization\x18\x01 \x01(\x0b\x32\x1f.nodecontroller.PoolUtilization\"`\n\x1dUpdatePoolUtilizationResponse\x12.\n\nassignment\x18\x01 \x01(\x0b\x32\x1a.nodecontroller.Assignment\x12\x0f\n\x07message\x18\x02 \x01(\t2\x86\x01\n\x0eNodeController\x12t\n\x15UpdatePoolUtilization\x12,.nodecontroller.UpdatePoolUtilizationRequest\x1a-.nodecontroller.UpdatePoolUtilizationResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node_controller_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POOLUTILIZATION._serialized_start=42
  _POOLUTILIZATION._serialized_end=219
  _ASSIGNMENT._serialized_start=221
  _ASSIGNMENT._serialized_end=277
  _UPDATEPOOLUTILIZATIONREQUEST._serialized_start=279
  _UPDATEPOOLUTILIZATIONREQUEST._serialized_end=363
  _UPDATEPOOLUTILIZATIONRESPONSE._serialized_start=365
  _UPDATEPOOLUTILIZATIONRESPONSE._serialized_end=461
  _NODECONTROLLER._serialized_start=464
  _NODECONTROLLER._serialized_end=598
# @@protoc_insertion_point(module_scope)
