# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import node_controller_pb2 as node__controller__pb2


class NodeControllerStub(object):
    """The NodeController service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdatePoolUtilization = channel.unary_unary(
                '/nodecontroller.NodeController/UpdatePoolUtilization',
                request_serializer=node__controller__pb2.UpdatePoolUtilizationRequest.SerializeToString,
                response_deserializer=node__controller__pb2.UpdatePoolUtilizationResponse.FromString,
                )


class NodeControllerServicer(object):
    """The NodeController service definition.
    """

    def UpdatePoolUtilization(self, request, context):
        """Pool Controllers call this to send their utilization data and receive assignments.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdatePoolUtilization': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePoolUtilization,
                    request_deserializer=node__controller__pb2.UpdatePoolUtilizationRequest.FromString,
                    response_serializer=node__controller__pb2.UpdatePoolUtilizationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nodecontroller.NodeController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NodeController(object):
    """The NodeController service definition.
    """

    @staticmethod
    def UpdatePoolUtilization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nodecontroller.NodeController/UpdatePoolUtilization',
            node__controller__pb2.UpdatePoolUtilizationRequest.SerializeToString,
            node__controller__pb2.UpdatePoolUtilizationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
