apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: img-rot
  namespace: default
spec:
  template:
    spec:
      containerConcurrency: 10000
      containers:
        - image: jovanvr97/img_rot_knative
    metadata:
      annotations:
        autoscaling.knative.dev/target: "1000"
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "1h"
